source-file ~/.config/tmux/tmux-plugins.conf
source-file ~/.config/tmux/tmux-theme.conf
source-file ~/.config/tmux/tmux-sessionx.conf
source-file ~/.config/tmux/tmux-copy-mode.conf

# some global settings
set -g mouse on
set-window-option -g mode-keys vi

# set tmux colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm*:Tc"

# enables yazi image preview
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# start window / pane index at 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# set prefix
set -g prefix C-a
bind C-a send-prefix

# reload tmux config 
bind t source-file ~/.config/tmux/tmux.conf

# alt j and k to switch between windows
bind -n M-h previous-window
bind -n M-l next-window
bind -n M-Left previous-window
bind -n M-Right next-window

# open panes and windows in current directory
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}" 
bind c new-window -c "#{pane_current_path}"

# resize panes
bind -r j resize-pane -D
bind -r k resize-pane -U
bind -r h resize-pane -L
bind -r l resize-pane -R

# ctrl + number to jump to window (alt + number reserved for harpoon)
bind -n C-1 select-window -t :1
bind -n C-2 select-window -t :2
bind -n C-3 select-window -t :3
bind -n C-4 select-window -t :4
bind -n C-5 select-window -t :5
bind -n C-6 select-window -t :6
bind -n C-7 select-window -t :7
bind -n C-8 select-window -t :8
bind -n C-9 select-window -t :9

# reset panes to tiled layout
bind r select-layout tiled

# toggle synchronize panes
bind p setw synchronize-panes

# Enable focus events
set -g focus-events on

# run TMUX plugin manager 
run '~/.config/tmux/plugins/tpm/tpm'

